---
- hosts: raspberry_pi
  roles:
    - raspberry-pi-up
- hosts:
    - raspbian
    - ubuntu
  roles:
    - debian-up
- hosts: raspbian
  roles:
    - raspbian-swap-down
    - raspbian-static-ip
- hosts: ubuntu
  roles:
    - ubuntu-swap-down
    - role: ansible-netplan
      become: yes
      netplan_enabled: true
      netplan_config_file: /etc/netplan/01-static-ip.yaml
      netplan_renderer: networkd
      netplan_configuration:
        network:
          version: 2
          ethernets:
            eth0:
              addresses:
                - {{ ansible_eth0.ipv4.address }}
              routes:
                - to: 0.0.0.0/0
                  via: 192.168.1.1
                  metric: 100
                - to: 0.0.0.0/0
                  via: 192.168.0.1
                  metric: 100

    
- hosts: all
  roles:
    - docker-up
- hosts: k3s_master
  roles:
    - k3s-master-up
  run_once: yes
- hosts: k3s_worker
  roles:
    - k3s-worker-up
- hosts:
    - k8s_master
    - k8s_worker
  roles:
    - k8s-commons-up
- hosts: k8s_master
  roles:
    - k8s-master-up
  run_once: yes
- hosts: k8s_worker
  roles:
    - k8s-worker-up
