---
- hosts: raspbian
  roles:
    - raspberry-pi-up
    - debian-up
    - raspbian-swap-down
- hosts: ubuntu
  roles:
    - debian-up
    - ubuntu-swap-down
- hosts: all
  roles:
    - docker-up
- hosts: k3s_master
  roles:
    - k3s-master-up
  run_once: yes
- hosts: k3s_worker
  roles:
    - k3s-worker-up
- hosts:
    - k8s_master
    - k8s_worker
  roles:
    - k8s-commons-up
- hosts: k8s_master
  roles:
    - k8s-master-up
  run_once: yes
- hosts: k8s_worker
  roles:
    - k8s-worker-up
