---
- name: update and upgrade OS
  apt:
    force_apt_get: yes
    update_cache: no
    upgrade: dist
  notify: reboot system
- name: install common apt packages
  apt:
    force_apt_get: yes
    name:
      - apt-transport-https
      - avahi-daemon
      - ca-certificates
      - curl
      - net-tools
      - nfs-common
      - open-iscsi
      - software-properties-common
- name: remove obsolete or unused packages
  apt:
    autoclean: yes
    autoremove: yes
    force_apt_get: yes
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  notify: reload avahi-daemon
- name: "set timezone to {{ timezone }}"
  timezone:
    name: "{{ timezone }}"
  notify: restart cron
- name: "set locale to {{ locale }}"
  lineinfile:
    line: "LANG={{ locale }}"
    path: /etc/default/locale
    regexp: '^\s*#?\s*LANG\s*='
  notify: reboot system
- name: set iscsi node startup to automatic
  lineinfile:
    line: "node.startup = automatic"
    path: /etc/iscsi/iscsid.conf
    regexp: '^\s*#?\s*node\s*\.\s*startup\s*='
- meta: flush_handlers
